// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCxgZfzWKWgJQyZ-hbEUoJOnRTBGyZ-uY',
    appId: '1:424721275614:web:6673eece70c9ce396fc04f',
    messagingSenderId: '424721275614',
    projectId: 'fruit-hub-c9be7',
    authDomain: 'fruit-hub-c9be7.firebaseapp.com',
    storageBucket: 'fruit-hub-c9be7.firebasestorage.app',
    measurementId: 'G-EEYS2TGD7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXCt9k1DzDQNJEcP1yghrR-VVNw5j_o7M',
    appId: '1:424721275614:android:65e3426ab9d3da616fc04f',
    messagingSenderId: '424721275614',
    projectId: 'fruit-hub-c9be7',
    storageBucket: 'fruit-hub-c9be7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUXBo9KHKL8n43w3W0OPh0JmzHthvroU',
    appId: '1:424721275614:ios:67321d7f4a1e2a596fc04f',
    messagingSenderId: '424721275614',
    projectId: 'fruit-hub-c9be7',
    storageBucket: 'fruit-hub-c9be7.firebasestorage.app',
    iosBundleId: 'com.example.furitsEcommerceApp',
  );
}
